---
apiVersion: v1
kind: Secret
metadata:
  name: redmine-secrets
type: Opaque
data:
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXk=
stringData:
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_PASSWORD: testpassword
  REDMINE_DB_DATABASE: /var/lib/postgresql/data/pgdata
